services:
  mongo:
    image: mongo:7.0
    container_name: gym-crm-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gymuser
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: gymdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
