spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    group:
      dev: security
      stage: security
      prod: security
  jpa:
    open-in-view: false
  application:
    name: trainer-workload

logging:
  pattern:
    console: "[%X{transactionId}] %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

server:
  port: 8081

queue-name: "trainer-workload"

dlq-name: "trainer-workload-dlq"
