spring:
  data:
    mongodb:
      uri: mongodb://gym_dev:dev_pass@dev-db-host:27017/gym_dev?authSource=admin
  rabbitmq:
    host: dev-rabbit.mycompany.com
    port: 5672
    username: devuser
    password: devpass
    listener:
      simple:
        concurrency: 3
        max-concurrency: 5

logging:
  level:
    com.gymcrm: DEBUG
    org.springframework: INFO
    org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG
    org.springframework.amqp.rabbit.connection: DEBUG