spring:
  profiles:
    group:
      local: integration
      dev: security, integration
      stage: security, integration
      prod: security, integration
  jpa:
    open-in-view: false
  application:
    name: trainer-workload

logging:
  pattern:
    console: "[%X{transactionId}] %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

security:
  jwt:
    secret: 8r7u6y5t4r3e2w1q0p9o8i7u6y5t4r3e

server:
  port: 8081

queue-name: "trainer-workload"
dlq-name: "trainer-workload-dlq"
