spring:
  mongodb:
    uri: mongodb://gymuser:pass@localhost:27017/gymdb?authSource=admin
  rabbitmq:
    addresses: amqp://localhost:5672
    username: gymuser
    password: pass
    listener:
      simple:
        concurrency: 1
        max-concurrency: 3

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG
    org.springframework.amqp.rabbit.connection: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/