spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  rabbitmq:
    host: rabbit.prod.mycompany.com
    port: 5672
    username: produser
    password: prodpass
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20

logging:
  level:
    root: INFO
    com.gymcrm: WARN
    org.springframework: WARN
    org.springframework.amqp.rabbit.core.RabbitAdmin: WARN
    org.springframework.amqp.rabbit.connection: WARN
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR

springdoc:
  swagger-ui:
    supported-submit-methods: []

security:
  jwt:
    secret: 8r7u6y5t4r3e2w1q0p9o8i7u6y5t4r3e