spring:
  jpa:
    open-in-view: false
  application:
    name: trainer-workload-service

logging:
  pattern:
    console: "[%X{transactionId}] %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

security:
  jwt:
    secret: 8r7u6y5t4r3e2w1q0p9o8i7u6y5t4r3e

server:
  port: 8081

springdoc:
  swagger-ui:
    supported-submit-methods: []

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
