spring:
  data:
    mongodb:
      uri: mongodb://gym_dev:dev_pass@dev-db-host:27017/gym_dev?authSource=admin
  rabbitmq:
    addresses: amqp://dev-rabbit.mycompany.com
    username: devuser
    password: devpass
    listener:
      simple:
        concurrency: 3
        max-concurrency: 5

logging:
  level:
    com.gymcrm: DEBUG
    org.springframework: INFO
    org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG
    org.springframework.amqp.rabbit.connection: DEBUG

security:
  jwt:
    secret: 8r7u6y5t4r3e2w1q0p9o8i7u6y5t4r3e